<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$url    = $config->getConfigValue('payment/myfatoorah_payment/is_testing') ? 'https://demo.myfatoorah.com/cardview/v1/session.js' : 'https://portal.myfatoorah.com/cardview/v1/session.js';
?>
<script  type="text/javascript">
    require.config({
        map: {
            '*': {
                'mfSessionFile': '<?php echo $url ?>'
            }
        }
    });
</script>
